<script src="/static/jquery/jquery.min.js" type="text/javascript"></script>
<script src="/static/jquery/jquery.form.js" type="text/javascript"></script>
<link href="/static/jquery/themes/icon.css" rel="stylesheet" type="text/css"/>
<link href="/static/jquery/themes/color.css" rel="stylesheet" type="text/css"/>
<link href="/static/jquery/themes/default/easyui.css" rel="stylesheet" type="text/css"/>
<script src="/static/jquery/jquery.easyui.min.js" type="text/javascript"></script>
<script src="/static/jquery/locale/easyui-lang-zh_CN.js" type="text/javascript"></script>